### ISSUE TITLE
RuntimeError: shape '[32, 1, 1000, 64]' is invalid for input of size 2273280

### ISSUE THREAD

**Issue by Tylersuard** [facebookresearch/mega#16]
303                 # B x L x S -> B x K x C x S
    304                 nc = seq_len // self.chunk_size
--> 305                 q = q.reshape(bsz, nc, self.chunk_size, self.zdim)
    306 
    307             if ctx_len < self.chunk_size:

RuntimeError: shape '[32, 1, 1000, 64]' is invalid for input of size 2273280

**Comment by Tylersuard** [comment]
This happens when I set chunk size to anything but -1.  I am trying to set the chunk size to some number between 2 and 10,000 because I am getting OOM errors, but this error happens every time.

**Comment by jeohalves** [comment]
Did you find out the solution for this error? I had the same problem.
