### ISSUE TITLE
Non-commercial license

### ISSUE THREAD

**Issue by mnaylor5** [facebookresearch/mega#7]
Hello, 

First of all, nice work on the MEGA paper - I enjoyed reading it, and the results are quite impressive. I have done some initial testing with MEGA, and it seems extremely promising: throughput on my long-document tasks is much faster with MEGA-chunk than I've seen with other linear self-attention mechanisms. 

However, I noticed that the license in this repository does not permit commercial use. Is there a possibility of relaxing this license to something more permissive, such as [fairseq's MIT License](https://github.com/facebookresearch/fairseq/blob/main/LICENSE)? Thanks!

**Comment by violet-zct** [comment]
Thanks for testing with Mega! I'll check this out with legal team and get to back to you later.

**Comment by mnaylor5** [comment]
Great! Thank you for looking into it. I'm really excited to use Mega more, but I definitely want to avoid license violations 😄

**Comment by violet-zct** [comment]
Just changed the license into MIT :-)

**Comment by mnaylor5** [comment]
Awesome, thanks so much!!
