### ISSUE TITLE
How to get test accuracy

### ISSUE THREAD

**Issue by aleksandar-terzic** [facebookresearch/mega#9]
I have trained several models on tasks from the LRA, but I'm not 100% sure how to obtain the accuracy on the test set. Do you have a command that you could provide me with for this purpose?

**Comment by XuezheMax** [comment]
Hi, 
here is an example to test the accuracy of a trained model
```python fairseq_cli/validate.py $DATA_PATH --task $TASK_NAME --batch-size $BATCH_SIZE --valid-subset test --path $CHECKPOINT_PATH```

**Comment by aleksandar-terzic** [comment]
Thank you

**Comment by aleksandar-terzic** [comment]
This does not work for LRA tasks

**Comment by aleksandar-terzic** [comment]
Thanks, but the command doesn't work for LRA tasks.

When I set --task to lra-text for example, I get the following error:

`validate.py: error: argument --task: invalid choice: 'lra-text' (choose from 'hubert_pretraining', 'speech_unit_modeling', 'translation', 'multilingual_translation', 'translation_lev', 'translation_from_pretrained_bart', 'audio_pretraining', 'nlu_finetuning', 'denoising', 'speech_to_text', 'text_to_speech', 'frm_text_to_speech', 'translation_multi_simple_epoch', 'simul_speech_to_text', 'simul_text_to_text', 'span_masked_lm', 'sentence_ranking', 'audio_finetuning', 'language_modeling', 'cross_lingual_lm', 'translation_from_pretrained_xlm', 'masked_lm', 'speech_to_speech', 'semisupervised_translation', 'sentence_prediction', 'sentence_prediction_adapters', 'online_backtranslation', 'multilingual_denoising', 'legacy_masked_lm', 'multilingual_language_modeling', 'multilingual_masked_lm', 'dummy_lm', 'dummy_masked_lm', 'dummy_mt')`

**Comment by aleksandar-terzic** [comment]
Thank you!
